#!/bin/bash

if [ -d "../build" ]; then
    echo "Directory already exists";
else
`mkdir ../build`;
fi

gcc ../src/tk_game.c -shared -o ../build/game.so -fPIC
gcc ../src/linux_main.c -o ../build/game -lX11 -L/usr/X11R6/lib -I/opt/X11R6/include